config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: "users/registrations",
  }
  devise_scope :user do
    get 'signups/sms_authentication', to: 'users/registrations#sms_authentication'
    post 'signups/sms_authentication', to: 'users/registrations#sms_authentication_create'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'products#index'

  resources :products do
    collection do
      get "category_children", defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: 'json' }
      get 'get_image', defaults: { format: 'json' }
      get 'header_second_category', defaults: { format: 'json' }
      get 'header_third_category', defaults: { format: 'json' }
    end
    member do
      get 'detail'
    end
  end

  resources :mypages, only: [:index] do
    collection do
      get 'logout'
      get 'listing'
      get 'card'
    end
    member do
      get 'profile'
      post 'update_profile'
      get 'identification'
      post 'update_identification'
    end
  end

  resources :users, only: [:index] do
    collection do
      get 'done'
    end
  end

  resources :addresses, only: [:index]

  resources :cards, only: [:new, :create, :destroy] do
    collection do
      get 'new_card'
      post 'pay'
    end
  end

  resources :purchases, only: [:show] do
    member do
      post 'pay'
      get 'done'
    end
  end

  resources :searches, only: [:index]

  resources :categories, only: [:index, :show]
end

app/views/shared/_footer-simple.html.haml
.footer-simple
  .footer-simple__box
    .footer-simple__box__info
      %ul
        %li プライバシーポリシー
        %li 利用規約
        %li 特定商取引に関する表記
    .footer-simple__box__logo
      = image_tag("logo_gray.svg", height: "65px", width: "80px")
    .footer-simple__box__mer
      © Fmarket, Inc.

app/views/shared/_footer.html.haml
.aside
  .aside__text
    .aside__text--1
      フリマアプリ
    .aside__text--2
      無料ダウンロード！
    .aside__text__logo
      = image_tag("fmarket_logo_red.svg", width: "200px")
  .aside__image
    = image_tag("shopping-site.jpg", height: "260px")
.toppage-footer
  .toppage-footer__top
    .toppage-footer__top__list
      Fmarketについて
      %ul
        %li 会社概要
        %li 採用情報
        %li プレリリース
        %li 公式ブログ
        %li ロゴ利用ガイドライン
      .toppage-footer__top__list__image
        %li 
          = icon('fab', 'twitter')
        %li 
          = icon('fab', 'facebook-square')
    .toppage-footer__top__list
      ヘルプ＆ガイド
      %ul
        %li ガイド
        %li らくらく便
        %li ゆうゆう便
        %li 大型便
        %li 車体取引ガイド
        %li あんしん・あんぜん宣言！
        %li 偽ブランド品撲滅への取り組み
        %li ボックス
    .toppage-footer__top__list
      プライバシーと利用規約
      .toppage-footer__top__list__box
        .toppage-footer__top__list__box__left
          %ul
            %li プライバシーポリシー
            %li メルカリ利用規約
            %li あんしんスマホサポート制度に関する利用特約
            %li コンプライアンスポリシー
        .toppage-footer__top__list__box__right
          %ul
            %li 個人データの安全管理に係る基本方針
            %li 特定商取引に関する表記
            %li 資金決済法に基づく表示
            %li 法令順守と犯罪抑止のために
    .toppage-footer__top__list
      国
      %ul
        %li 日本
        %li United States
  .toppage-footer__bottom
    = link_to root_path,class: "toppage-footer__bottom__link" do
      = image_tag("logo_red.svg", width: "40px")
      .toppage-footer__bottom__link__text
        Fmarket
    .toppage-footer__bottom__logo
      © 2020 Fmarket

app/views/shared/_header-simple.html.haml
.header-simple
  .header-simple__logo
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg", width: "185px", height: "49px"

app/views/shared/_header.html.haml
%header
  .content
    .top-content
      .top-content__logo
        = link_to root_path do
          = image_tag("fmarket_logo_red.svg", class:"top-content__logo")
      = search_form_for(@q, url: searches_path, class: 'top-content__search') do |f|
        = f.search_field :product_name_cont, placeholder:'何かお探しですか？', class: 'top-content__search__keyword', id: 'top-content__search__keyword'
        %label.top-content__search__icon
          = icon('fas', 'search')
          = f.submit :submit, style: "display: none;"
    .bottom-content
      .bottom-content__item
        .bottom-content__item__category
          .header-category__link
            = link_to categories_path ,class: "bottom-content__item__category__part" do
              = icon('fas', 'list', class: 'bottom-content__item__category__part__icon')
              カテゴリーから探す
          .header-category__box
            .header-category__box__first
              - @category.each do |category|
                .header-category__box__first__list{data: {category: {id: category.id}}}
                  = link_to category_path(category.id) do
                    = category.name
            .header-category__box__second
            .header-category__box__third

        .bottom-content__item__brand
          = link_to "#", class: "bottom-content__item__brand__part" do
            = icon('fas', 'tag', class: 'bottom-content__item__brand__part__icon')
            ブランドから探す
      - if user_signed_in?
        %ul.bottom-content__list
          %li.bottom-content__list__favorite
            = link_to "#", class: "bottom-content__list__favorite__part" do
              = icon('far', 'heart', class: 'bottom-content__list__favorite__part__icon')
              いいね！一覧
          %li.bottom-content__list__notice
            = link_to "#", class: "bottom-content__list__notice__part" do
              = icon('far', 'bell', class: 'bottom-content__list__notice__part__icon')
              お知らせ
          %li.bottom-content__list__todo
            = link_to "#", class: "bottom-content__list__todo__part" do
              = icon('fas', 'check', class: 'bottom-content__list__todo__part__icon')
              やることリスト
          %li.bottom-content__list__mypage
            = link_to mypages_path, class: 'bottom-content__list__mypage__part' do
              = image_tag("",class:"bottom-content__list__mypage__part__img")
              マイページ
      - else
        %ul.bottom-content__list
          %li.bottom-content__list__new-registration
            = link_to "新規登録" , users_path, class: 'btn'
          %li.bottom-content__list__login
            = link_to "ログイン", new_user_session_path, class: 'btn'
            