config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: "users/registrations",
  }
  devise_scope :user do
    get 'signups/sms_authentication', to: 'users/registrations#sms_authentication'
    post 'signups/sms_authentication', to: 'users/registrations#sms_authentication_create'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'products#index'

  resources :products do
    collection do
      get "category_children", defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: 'json' }
      get 'get_image', defaults: { format: 'json' }
      get 'header_second_category', defaults: { format: 'json' }
      get 'header_third_category', defaults: { format: 'json' }
    end
    member do
      get 'detail'
    end
  end

  resources :mypages, only: [:index] do
    collection do
      get 'logout'
      get 'listing'
      get 'card'
    end
    member do
      get 'profile'
      post 'update_profile'
      get 'identification'
      post 'update_identification'
    end
  end

  resources :users, only: [:index] do
    collection do
      get 'done'
    end
  end

  resources :addresses, only: [:index]

  resources :cards, only: [:new, :create, :destroy] do
    collection do
      get 'new_card'
      post 'pay'
    end
  end

  resources :purchases, only: [:show] do
    member do
      post 'pay'
      get 'done'
    end
  end

  resources :searches, only: [:index]

  resources :categories, only: [:index, :show]
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def profile
    @user = User.new
  end

  def update_profile
    @user = User.find(params[:id])
    if @user.id == current_user.id
      current_user.update(user_params)
      redirect_to profile_mypage_path(current_user.id)
    else
      redorect_to profile_mypage_path(current_user.id)
    end
  end

  def identification
    @address = Address.new
  end

  def update_identification
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to identification_mypage_path
    else
      redirect_to identification_mypage_path
    end
  end

  def listing
    @products = current_user.products
  end

  def card
    @card = current_user.card
    if @card.present?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)
    end
  end


  private
  def user_params
    params.require(:user).permit(:nickname)
  end

  def address_params
    params.require(:address).permit(:zip_code, :prefecture, :city, :block_num, :building_name).merge(user_id: current_user.id)
  end

end

app/views/mypages/_side-bar.html.haml
.side-bar
  .side-bar__nav
    %ul.side-bar__nav__list
      %li
        = link_to mypages_path, class: 'link' do
          マイページ
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          お知らせ
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          やることリスト
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          いいね！一覧
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          出品する
          = icon('fas', 'chevron-right')
      %li
        = link_to listing_mypages_path, class: 'link' do
          出品した商品-出品中
          = icon('fas', 'chevron-right')
      %li
        = link_to "#", class: 'link' do
          出品した商品-取引中
          = icon('fas', 'chevron-right')
      %li
        = link_to "#", class: 'link' do
          出品した商品-売却済み
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          購入した商品-取引中
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          購入した商品-過去の取引
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          ニュース一覧
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          評価一覧
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          ガイド
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          お問い合わせ
          = icon('fas', 'chevron-right')
    .side-bar__nav__head
      メルペイ
    %ul.side-bar__nav__list
      %li
        = link_to '#', class: 'link' do
          売上・振込申請
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          ポイント
          = icon('fas', 'chevron-right')
    .side-bar__nav__head
      設定
    %ul.side-bar__nav__list
      %li
        = link_to profile_mypage_path(current_user.id), class: 'link' do
          プロフィール
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          発送元・お届け先住所変更
          = icon('fas', 'chevron-right')
      %li
        = link_to card_mypages_path, class: 'link' do
          支払い方法
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          メール/パスワード
          = icon('fas', 'chevron-right')
      %li
        = link_to identification_mypage_path(current_user.id), class: 'link' do
          本人情報
          = icon('fas', 'chevron-right')
      %li
        = link_to '#', class: 'link' do
          電話番号の確認
          = icon('fas', 'chevron-right')
      %li
        = link_to  logout_mypages_path, class: 'link' do
          ログアウト
          = icon('fas', 'chevron-right')

app/views/mypages/card.html.haml
.mypage-wrapper
  = render 'shared/header'
  .mypage-main
    = render 'side-bar'
    .mypage-main__container
      .mypage-main__container__card-box
        .mypage-main__container__card-box__head
          支払い方法
        -if @card_information.blank?
          .mypage-main__container__card-box__content
            .mypage-main__container__card-box__content__top
              .mypage-main__container__card-box__content__top__text
                クレジットカード一覧
              .mypage-main__container__card-box__content__top__add
                .mypage-main__container__card-box__content__top__add__btn
                  = link_to new_card_cards_path do
                    .far.fa-credit-card
                    クレジットカードを追加する
                
            .mypage-main__container__card-box__content__bottom
              = link_to "#" do
                支払方法について
                .fa.fa-chevron-right
        -else
          .mypage-main__container__card-box__content
            .mypage-main__container__card-box__content__top
              .mypage-main__container__card-box__content__top__text
                クレジットカード一覧
              .mypage-main__container__card-box__content__top__card
                .mypage-main__container__card-box__content__top__card__name
                  VISA
                .mypage-main__container__card-box__content__top__card__num
                  ="************"+@card_information.last4
                .mypage-main__container__card-box__content__top__card__date
                  ="#{@card_information.exp_month}/#{@card_information.exp_year%100}"
                .mypage-main__container__card-box__content__top__card__delete
                  = link_to card_path(@card), {method: :delete} do
                    削除する
            .mypage-main__container__card-box__content__bottom
              = link_to "#" do
                支払方法について
                .fa.fa-chevron-right
  = render 'shared/footer'

app/views/mypages/change_address.html.haml
.mypage-wrapper
  = render 'shared/header'
  .mypage-main
    = render 'side-bar'

    .form
      .form-group
        %label お名前
        %span.form-required 必須
        %br
        -# =current_user.l_name_kanji + current_user.f_name_kanji
      .form-group
        %label お名前カナ
        %span.form-required 必須
        %br
        -# =current_user.l_name_kana + current_user.f_name_kana
      .form-group
        %label{for: "zip_code"} 郵便番号
        %span.form-required 必須
        -# = f.text_field :postal_code, class: "input-default",  placeholder: "例) 1234567"
      .form-group
        %label{for: "prefecture"} 都道府県
        %span.form-required 必須
        .select-wrap
          -# = f.select :prefecture, Address.prefectures.keys,{prompt: '---',class:"select-wrap"}
          %i.fa.fa-angle-down
      .form-group
        %label{for: "city"} 市区町村
        %span.form-required 必須
        -# = f.text_field :city, class: "input-default",  placeholder: "例) 1234567"
      .form-group
        %label{for: "address1_label"} 番地
        %span.form-required 必須
        -# = f.text_field :street, class: "input-default",  placeholder: "例) 1234567"
      .form-group
        %label{for: "address2_label"} 建物名
        %span.form-arbitrary 任意
        -# = f.text_field :building, class: "input-default",  placeholder: "例) 1234567"
      .form-group
        %label{for: "phone_number"} 電話
        %span.form-arbitrary 任意
        -# = f.text_field :building, class: "input-default",  placeholder: "例) 1234567"
      -# = f.submit "変更する", class:"btn-default btn-red form-group"



              <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div class="label"><%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, :placeholder => 'メールアドレスを入力' %></div>

          <div class="label"><%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
          <%= f.password_field :password, autocomplete: "off", :placeholder => 'パスワードを入力' %></div>

          <div class="label"><%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", :placeholder => 'パスワードを入力（確認）' %></div>

          <div class="label"><%= f.label :nickname %><br />
          <%= f.text_field :nickname %></div>
          <div class="field">
          <%= f.file_field :avatar %>
          </div>

          <div class="submit">
          <div class="actions">
          <%= f.submit %>
          </div></div>

app/views/mypages/identification.html.haml
.mypage-wrapper
  = render 'shared/header'
  - breadcrumb :identification
  = render 'layouts/breadcrumbs'
  .mypage-main
    = render 'side-bar'
    .mypage-main__container
      .mypage-main__container__identification
        .mypage-main__container__identification__top
          本人情報
        = form_with model: @address, url: update_identification_mypage_path, local: true do |f|
          .mypage-main__container__identification__main
            .mypage-main__container__identification__main__head
              .mypage-main__container__identification__main__head__text-exp
                お客さまの本人情報をご登録ください。
                %br
                登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
              .mypage-main__container__identification__main__head__text-right
                = link_to "#" do
                  本人確認書類のアップロードについて
                  .fa.fa-chevron-right
            .mypage-main__container__identification__main__form-group
              %label
                お名前
              %p
                = current_user.last_name
                = current_user.first_name
            .mypage-main__container__identification__main__form-group
              %label
                お名前カナ
              %p
                = current_user.last_name_kana
                = current_user.first_name_kana
            .mypage-main__container__identification__main__form-group
              %label
                生年月日
              %p
                = "#{current_user.birth_year}/"
                = "#{current_user.birth_month}/"
                = current_user.birth_day
            .mypage-main__container__identification__main__form-group
              %label
                郵便番号
              %span 任意
              = f.text_field :zip_code, placeholder: "例）1234567"
            .mypage-main__container__identification__main__form-group
              %label
                都道府県
              %span 任意
              = f.collection_select :prefecture_id, Prefecture.all, :name, :name, {prompt: "-------"}
            .mypage-main__container__identification__main__form-group
              %label
                市区町村
              %span 任意
              = f.text_field :city, placeholder: "例）横浜市緑区"
            .mypage-main__container__identification__main__form-group
              %label
                番地
              %span 任意
              = f.text_field :block_num, placeholder: "例）青山1-1-1"
            .mypage-main__container__identification__main__form-group
              %label
                建物名
              %span 任意
              = f.text_field :building_name, placeholder: "例）柳ビル103"
            .mypage-main__container__identification__main__btn
              = f.submit '登録する'
            .mypage-main__container__identification__main__bottom
              = link_to "#" do
                本人情報の登録について
                .fa.fa-chevron-right



  = render 'shared/footer'

app/views/mypages/index.html.haml
.mypage-wrapper
  = render 'shared/header'
  - breadcrumb :mypage
  = render 'layouts/breadcrumbs'
  .mypage-main
    = render 'side-bar'
    .mypage-main__container
      .mypage-main__container__icon
        .mypage-main__container__icon__content
          = link_to "#", class: "#" do
            .mypage-main__container__icon__content__image
              = icon('fas', 'user', class: "icon")
            .mypage-main__container__icon__content__name
              = "#{current_user.nickname}でログイン中"
            .mypage-main__container__icon__content__text
              評価  ０出品数  ０
      .mypage-main__container__tabs
        .mypage-main__container__tabs__tab
          .mypage-main__container__tabs__tab__info.active
            お知らせ
          .mypage-main__container__tabs__tab__todo
            やることリスト
        .mypage-main__container__tabs__contents
          %ul.mypage-main__container__tabs__contents__box
            %li
              = link_to "#" do
                .mypage-main__container__tabs__contents__box__list
                  = image_tag("logo_red.svg", size: "48x48")
                  .mypage-main__container__tabs__contents__box__list__text
                    %p
                      事務局から個別メッセージ「《3日間限定！！ポイント倍増》招待コード「あけおめ」」を入力してフリペイ登録すると合計P2,000もらえる」
                    %time
                      = icon('far', 'clock')
                      %span 1日前
                  = icon('fas', 'chevron-right')
            %li.go-list
              .go-list__btn
                = link_to "#" do
                  一覧を見る
      .mypage-main__container__box
        .mypage-main__container__box__head
          購入した商品
        .mypage-main__container__box__tabs
          .mypage-main__container__box__tabs__tab
            .mypage-main__container__box__tabs__tab__trading
              取引中
            .mypage-main__container__box__tabs__tab__past
              過去の取引
        .mypage-main__container__box__content
  = render 'shared/footer'

app/views/mypages/listing.html.haml
.mypage-wrapper
  = render 'shared/header'
  - breadcrumb :listing
  = render 'layouts/breadcrumbs'
  .mypage-main
    = render 'side-bar'
    .mypage-main__container
      .mypage-main__container__box
        .mypage-main__container__box__head
          出品した商品
        .mypage-main__container__box__lists
          = link_to "#", class: "mypage-main__container__box__lists__active" do
            出品中
          = link_to "#", class: "mypage-main__container__box__lists__inactive" do
            取引中
          = link_to "#", class: "mypage-main__container__box__lists__inactive" do
            売却済み
        - unless @products.any?
          .mypage-main__container__box__no-product
            出品中の商品はありません
        - else
          .mypage-main__container__box__products
            - @products.each do |product|
              - if product.selling_status_id == "1"
                = link_to detail_product_path(product.id), class: "mypage-main__container__box__products__product" do
                  .mypage-main__container__box__products__product__image
                    = image_tag "#{product.images[0].image}"
                  .mypage-main__container__box__products__product__content
                    .mypage-main__container__box__products__product__content__name
                      = product.product_name
                    .mypage-main__container__box__products__product__content__icon
                      .far.fa-heart
                        0
                      .far.fa-comment-alt
                        0
                  .mypage-main__container__box__products__product__arrow
                    .fas.fa-angle-right
  = render 'shared/footer'

app/views/mypages/logout.html.haml
.mypage-wrapper
  = render 'shared/header'
  - breadcrumb :logout
  = render 'layouts/breadcrumbs'
  .mypage-main
    = render 'side-bar'
    .mypage-main__container
      .mypage-main__container__logout-box
        .mypage-main__container__logout-box__btn
          = link_to destroy_user_session_path, method: :delete do
            ログアウト

app/views/mypages/on_sale_products.html.haml
.mypage-wrapper
    = render 'shared/header'
    .mypage-main
        .maypage-tabs-container
            %h2.status-tab-head
                出品した商品
            %ul.status-tabs
                出品中
                取引中
                売却済み
            .products-content
                
        = render 'side-bar'

    = render 'shared/footer'

app/views/mypages/profile.html.haml
.mypage-wrapper
  = render 'shared/header'
  - breadcrumb :profile
  = render 'layouts/breadcrumbs'
  .mypage-main
    = render 'side-bar'
    .mypage-main__profile
      .mypage-main__profile__text
        プロフィール
      = form_with model: @user, url: update_profile_mypage_path, local: true do |f|
        .mypage-main__profile__box
          .mypage-main__profile__box__top
            .mypage-main__profile__box__top__human
              .mypage-main__profile__box__top__human__image
                = icon('fas', 'user', class: "icon")
              .mypage-main__profile__box__top__human__name
                = f.text_field :nickname, value:current_user.nickname
          .mypage-main__profile__box__comment
            .mypage-main__profile__box__comment__text
              = f.text_area :profile, placeholder:"例）hello!!"
            .mypage-main__profile__box__comment__btn
              = f.submit '変更する', class: "submit-btn"

  = render 'shared/footer'