config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: "users/registrations",
  }
  devise_scope :user do
    get 'signups/sms_authentication', to: 'users/registrations#sms_authentication'
    post 'signups/sms_authentication', to: 'users/registrations#sms_authentication_create'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'products#index'

  resources :products do
    collection do
      get "category_children", defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: 'json' }
      get 'get_image', defaults: { format: 'json' }
      get 'header_second_category', defaults: { format: 'json' }
      get 'header_third_category', defaults: { format: 'json' }
    end
    member do
      get 'detail'
    end
  end

  resources :mypages, only: [:index] do
    collection do
      get 'logout'
      get 'listing'
      get 'card'
    end
    member do
      get 'profile'
      post 'update_profile'
      get 'identification'
      post 'update_identification'
    end
  end

  resources :users, only: [:index] do
    collection do
      get 'done'
    end
  end

  resources :addresses, only: [:index]

  resources :cards, only: [:new, :create, :destroy] do
    collection do
      get 'new_card'
      post 'pay'
    end
  end

  resources :purchases, only: [:show] do
    member do
      post 'pay'
      get 'done'
    end
  end

  resources :searches, only: [:index]

  resources :categories, only: [:index, :show]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'

  def new
  end

  def new_card
  end
  
  def create
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
    if params['payjp-token'].blank?
      redirect_to action: "new_card"
    else
      user_id = current_user.id
      customer = Payjp::Customer.create(
      description: '登録テスト', 
      card: params['payjp-token'],
      ) 
      @card = Card.new(user_id: user_id, customer_id: customer.id, card_id: customer.default_card)
      path = Rails.application.routes.recognize_path(request.referer)
      if @card.save
        if path[:controller] == "cards" && path[:action] == "new"
          redirect_to controller: :users, action: :done
        elsif path[:controller] == "cards" && path[:action] == "new_card"
          redirect_to controller: :mypages, action: :card
        end
      else
        redirect_to action: "new_card"
      end
    end
  end

  def destroy
    @card = current_user.card
    if @card.present?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
    redirect_to controller: :mypages, action: :card
  end
end

app/views/cards/_header-card.html.haml
.signup-registration-header
  .signup-registration-header__logo
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg"
  .progress-bar
    %ul
      %li.progress-bar__list.progress-bar__list--finished
        会員情報
        .progress-bar__progress-status
      %li.progress-bar__list.progress-bar__list--finished
        電話番号認証
        .progress-bar__progress-status
      %li.progress-bar__list.progress-bar__list--finished
        お届け先住所入力
        .progress-bar__progress-status
      %li.progress-bar__list.progress-bar__list--active
        支払い方法
        .progress-bar__progress-status
      %li.progress-bar__list
        完了
        .progress-bar__progress-status

app/views/cards/new.html.haml
.signup-wrapper
  = render 'cards/header-card'
  .signup-main
    .signup-main__container
      .signup-main__container__top
        支払い方法
      = form_with model: @card, url: cards_path, local: true, class: "signup-form", html: { name: 'inputForm' } do |f|
        .signup-main__container__box
          .signup-main__container__form-group
            = f.label 'カード番号'
            %span.signup-main__container__form-require 必須
            %br
            = f.text_field :card_num, autofocus: true, placeholder: '例)半角数字のみ', class: 'input-default', id: "card_number"
            %ul.signup-main__container__card-box
          .signup-main__container__form-group
            = f.label '有効期限'
            %span.signup-main__container__form-require 必須
            %br
            .signup-main__container__date-box
              .signup-main__container__date-box__select-wrap
                = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'form-signup__month__select'
                = icon 'fas', 'chevron-down'
                %span 月
              .signup-main__container__date-box__select-wrap
                = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'form-signup__month__select'
                = icon 'fas', 'chevron-down'
                %span 年
          .signup-main__container__form-group
            = f.label 'セキュリティーコード'
            %span.signup-main__container__form-require 必須
            %br
            = f.text_field :cvc, placeholder: 'カード背面4桁もしくは3桁の番号', class: 'input-default', id: 'cvc'
          .signup-main__container__content__form-group
            .signup-main__container__content__form-group__text-right
              = link_to "#", class: "question" do
                ?
              = link_to "#" do
                カード裏面の番号とは?
          .signup-main__container__content
            #card_token
            = submit_tag '次へ進む', id: 'token_submit', class: "input-default btn-next"
  = render 'shared/footer-simple'

app/views/cards/new_card.html.haml
.mypage-wrapper
  = render 'shared/header'
  .mypage-main
    = render 'mypages/side-bar'
    .mypage-main__container
      .mypage-main__container__new-card-box
        .mypage-main__container__new-card-box__head
          クレジットカード情報入力
        = form_with model: @card, url: cards_path,method: 'post', local: true, class: "signup-form", html: { name: 'inputForm' } do |f|
          .mypage-main__container__new-card-box__main
            .mypage-main__container__new-card-box__main__form-group
              = f.label 'カード番号'
              %span.mypage-main__container__new-card-box__main__form-require 必須
              %br
              = f.text_field :card_number, autofocus: true, placeholder: '例)半角数字のみ', class: 'input-default', id: "card_number"
            .mypage-main__container__new-card-box__main__form-group
              = f.label '有効期限'
              %span.mypage-main__container__new-card-box__main__form-require 必須
              %br
              .mypage-main__container__new-card-box__main__date-box
                .mypage-main__container__new-card-box__main__date-box__select-wrap
                  = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'card-select'
                  %span 月
                .mypage-main__container__new-card-box__main__date-box__select-wrap
                  = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'card-select'
                  %span 年
            .mypage-main__container__new-card-box__main__form-group
              = f.label 'セキュリティーコード'
              %span.mypage-main__container__new-card-box__main__form-require 必須
              %br
              = f.text_field :cvc, placeholder: 'カード背面4桁もしくは3桁の番号', class: 'input-default', id: 'cvc'
              .mypage-main__container__new-card-box__main__form-group__bottom-text
                = link_to "#", class: "question" do
                  ?
                = link_to "#" do
                  カード裏面の番号とは?
            .mypage-main__container__new-card-box__main__btn
              #card_token
              = submit_tag '追加する', id: 'token_submit', class: "input-default btn-red"
  = render 'shared/footer'